### Home
GET http://localhost:8080/

### Todas las peliculas y series
GET http://localhost:8080/contenidos

### Filtrar contenido por id
GET http://localhost:8080/contenidos/1

### Filtrar contenido por categoria
GET http://localhost:8080/contenidos/query?categoria=pelicula

### Filtrar contenido por titulo, genero o categoria 
GET http://localhost:8080/contenidos/query?genero=Drama

### Agregar pelicula
POST http://localhost:8080/contenidos/
Content-Type:application/json
{
    "titulo":"Guasón",
    "poster":"./posters/7.jpg",
    "categoria":1, // id de la categoria Pelicula
    "genero":3, // id del genero Ciencia Ficcion
    "resumen":"Arthur Fleck (Phoenix) es un hombre ignorado por la sociedad, cuya motivación en la vida es hacer reír. Pero una Serie de trágicos acontecimientos le llevarán a ver el mundo de otra forma. Película basada en el popular personaje de DC Comics Joker, conocido como archivillano de Batman, pero que en este film tomará un cariz más realista y oscuro.", 
    "duracion":121,
    "trailer":"https://www.youtube.com/embed/zAGVQLHvwOY",
    "reparto":[10,20,30]
} 

### Eliminar contenidos
DELETE http://localhost:8080/contenidos/eliminar/100

### Actualizar de contenidos parcial o completa
PATCH http://localhost:8080/contenidos/actualizar/26
Content-Type: application/json
{
    "genero":10
}
### Crear Actor
POST http://localhost:8080/actores/crear
Content-Type: application/json

{
    "nombre_actor":"Rodrigo de la serna"
}